export enum ErrorId {
  Unauthorized = 'Unauthorized',
  DataNotFound = 'DataNotFound',
  StillCoolingDown = 'StillCoolingDown',
  DataAlreadyExist = 'dataAlreadyExist',
  UserNotFound = 'UserNotFound',
  AccountAlreadyExists = 'UserAlreadyExists',
  InvalidCredentials = 'InvalidCredentials',
  MultipleLogin = 'MultipleLogin',
  InvalidToken = 'InvalidToken',
  NetworkError = 'NetworkError',
  InternalServerError = 'InternalServerError',
  NotEnoughResource = 'NotEnoughResource',
  InvalidArgument = 'InvalidArgument',
  DatabaseError = 'DatabaseError',
  NotSupported = 'NotSupported',
  InvalidFileFormat = 'InvalidFileFormat',
  InvalidFileData = 'InvalidFileData',
  InvalidJson = 'InvalidJson',
  DataExpired = 'DataExpired',
}
